TOGEDU/Cloning

- App.js
- package-lock.json
- package.json
- pages/Record.js
- pages/RecordingScreen.js
- #16 
- RecordingScreen.js
- 녹음완료버튼 누르면 Record.js화면에 있는 진행퍼센트 늘어나는것까지 구현완료
- 녹음기능구현할것
closed #
> 음성 녹음 화면 페이지 일부 구현

- App.js
- pages/Record.js
- pages/RecordingScreen.js
- #14 
- Record.js
- RecordingScreen.js
- 음성녹음페이지에서 완료버튼 누르면 음성기록진행현황페이지의 해당 아이탬 삭제 및 progress 늘어남
- App.js
- 헤더색상변경완료 (DailyQuestionList.js, Record.js)
- 이제 음성녹음기능 구현할것
closed #
> 음성 기록 진행 현황 페이지 수정

- App.js
- package-lock.json
- package.json
- pages/Diary.js
- pages/DiaryList.js
- #9 
- 일기 작성 페이지 구현
- 사진첨부 기능, 상단부 터치영역 수정
closed #
> 육아일기 작성 페이지 UI구현

- App.js
- pages/Signup/Child/ChildIdPw.js
- pages/Splash.js
- #27 
- 스플래시 화면 디자인 수정
- 
closed #
> 스플래시 화면 디자인 수정

- pages/Home.js
- #메인
- 오늘의 질문 멘트 수정
- 
closed #
> 메인화면 내용 수정

- App.js
- package.json
> Fix: error

- App.js
- pages/ChildChat.js
- pages/Login.js
- #21 
- 부모, 자식 로그인 구별
- 
closed #
> Feat: 로그인 자식, 부모 구별

- package-lock.json
- package.json
- pages/RecordingScreen.js
- #16 
- RecordingScreen.js
- 디자인 수정?
- 오류나면 npx expo start 이걸로 함 해보세요
closed #
> Fix: 음성녹음기능

- package.json
- pages/RecordingScreen.js
- #16 
- 녹음화면버튼 수정
- statusbar 색상 변경하려고 했으나 header가 있으면 변경할 수 없다고함.. 방법을 찾아봐야할듯 노션참조
closed #
> 녹음화면버튼수정, statusbar

- App.js
- package-lock.json
- package.json
- pages/ChildChat.js
- pages/ChildMyPage.js
- pages/Login.js
- pages/Signup/Child/ChildIdPw.js
- pages/Signup/Child/ChildInfo.js
- pages/Signup/Child/ChildSearchCode.js
- pages/Signup/Parent/ParentChildInfo.js
- pages/Signup/Parent/ParentIdPw.js
- pages/Signup/Parent/ParentPush.js
- pages/Signup/Parent/ParentSearchCode.js
- pages/TodayQuestion.js
- pages/TodayQuestionList.js
- #
- api 연결 및 배경 여백 수정
- ChildChat이랑 ChildMypage에서 위아래로 여백은 없어지게 해놨는데 로고크기나 그런거 다시 수정해야 할듯.. 여백도 언제 다시 생길지는 모르겠지만ㅎㅎ
closed #
> api 연결 및 배경 여백 수정

- App.js
- AuthContext.js
- pages/Achieve.js
- pages/Diary.js
- pages/DiaryList.js
- pages/Login.js
- pages/Signup/Child/ChildIdPw.js
- pages/Signup/Parent/ParentIdPw.js
- pages/Signup/SignupFinish.js
- pages/Signup/SignupStart.js
- pages/Splash.js
- pages/TodayQuestion.js
- pages/TodayQuestionList.js
- pages/WriteFinish.js
> 토큰 관리 로직 추가

- api.js
- package-lock.json
- package.json
- pages/Diary.js
- pages/DiaryList.js
- pages/MyPage.js
- pages/Signup/Child/ChildIdPw.js
- #
- 부모 마이페이지 데이터 가져오기
- 푸시알림 상태 변경
- 알림 시간 변경
- 자녀 정보 수정 
- 
closed #
> 부모 마이페이지 api 연결

- pages/Diary.js
- #9 
- 일기 작성 api 연결
- 
closed #
> Feat: 일기 작성 api 연결

- api.js
- pages/ChatList.js
- pages/ChildChat.js
- pages/Record.js
- pages/RecordingScreen.js
> chatlist, record api연결완료

- App.js
- api.js
- package-lock.json
- package.json
- pages/ChatList.js
- pages/ChatRoomScreen.js
- pages/ChildChat.js
> seoyeon 브랜치 내용으로 변경

- App.js
- api.js
- package-lock.json
- package.json
- pages/ChatRoomScreen.js
- pages/Record.js
- pages/RecordingScreen.js
> 애니메이션, date 수정 pull

- api.js
- package-lock.json
- package.json
- pages/TodayQuestion.js
- #
- 오늘의 질문 녹음 버튼 추가
- api 추가해야됨
- 디자인 수정해야됨
closed #
> 오늘의 질문 녹음 버튼 추가

- api.js
- package-lock.json
- package.json
- pages/ChildChat.js
> 채팅음성재생api 연결중

- pages/ChildChat.js
- pages/ChildMyPage.js
- pages/MyPage.js
- pages/TodayQuestionList.js
> Feat: 마이페이지 ui수정 및 childchat 음성재생api연결 성공

- pages/ChildChat.js
> Fix: ChildChat복원

- pages/Diary.js
> Feat: 다이어리 stt 기능 추가

- api.js
- pages/TodayQuestion.js
> 오늘의 질문 디자인 수정

- pages/Signup/Parent/ParentSearchCode.js
> Fix: 코드확인 수정

- pages/Signup/Parent/ParentIdPw.js
- pages/Signup/Parent/ParentSearchCode.js
> Feat: 회원가입 이름 추가

- pages/ChildChat.js
> Feat: childchat로딩스피너

- api.js
- pages/ChatRoomScreen.js
- pages/ChildChat.js
- pages/ChildMyPage.js
> 아이마이페이지api연결완료

- api.js
- pages/ChatRoomScreen.js
- pages/ChildChat.js
- pages/Home.js
> Fix:childchat
